### ISSUE TITLE
Any reason not to use the monolithic build?

### ISSUE THREAD

**Issue by drwave** [simpassi/mule#1]
Glanced at your Xcode project - might I suggest building your USD library monolithically, like I suggest here in Step 3:

https://github.com/drwave/usd-sketchup/blob/master/README.md

That will simplify your project file...

**Comment by drwave** [comment]
Hmm, I noticed you've got a little Python script to to do just that - are all these other libraries needed?

<img width="574" alt="screen shot 2019-01-07 at 9 24 12 am" src="https://user-images.githubusercontent.com/1679418/50782886-1defee80-125e-11e9-93b9-8568f9d8e782.png">

**Comment by virokannas** [comment]
The other libraries might not be needed - I literally just pulled the whole folder contents into the project. There's also a build step to relink the .dylibs into the correct location in the app bundle.

There's a different issue I'm facing now, to do with the way Swift/C/C++ bridging is done and somehow rendering direct USD C++ calls disfunctional. Might be that I'll need to still use Objective-C for this.

**Comment by virokannas** [comment]
The other issue was unrelated, just needed all the pluginInfo files where the dylib can find them. In the end, yes, only libusd_ms is needed so that's the only dependency now. Thanks for pointing that out @drwave !
